server:
  port: 9000
spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - POST
              - GET
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: hospitalMicroservice
          uri: http://localhost:8081/
          predicates:
            - Path=/hospital/**

        - id: usersMicroservice
          uri: http://localhost:8082/
          predicates:
            - Path=/users/**